# Directoare
REPORTS_DIR="../reports"
BACKUP_DIR="../backups"
CONFIG_DIR="../config"
LOG_ARCHIVE_DIR="../log_archive"

# Health / Monitoring
DISK_THRESHOLD=80
MEMORY_THRESHOLD=80

# Backup
BACKUP_PERMISSIONS="600"

# Services
SERVICES=("sshd" "cron" "nginx")

# Logging
LOG_FILE="../log_archive/activity.log"
LOG_MAX_SIZE_MB=10

# Timestamp
TIMESTAMP_FORMAT="+%Y-%m-%d_%H-%M-%S"
